# Generated by Django 6.0.3 on 2026-04-02 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_symptom_patientsymptom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="confidence_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="risk_level",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Low",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="symptom_breathlessness",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="symptom_chest_pain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="symptom_cough",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="symptom_fatigue",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="symptom_fever",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="symptom_headache",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="symptom_nausea",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="symptom_sweating",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="bmi",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="bp_diastolic",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="bp_systolic",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="cholesterol",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="heart_rate",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_records",
                to="core.patient",
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="sugar_level",
            field=models.FloatField(default=0),
        ),
    ]
