# Generated by Django 6.0.3 on 2026-04-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rebuild_healthrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthrecord",
            name="date",
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="confidence",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="risk_level",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                max_length=10,
            ),
        ),
    ]
